version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.3
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./requirements.txt:/opt/airflow/requirements.txt
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID}:0"
  group_add:
    - "${DOCKER_GID}"
  networks:
    - orchestrator-net
    - ingest-net

services:
  airflow-db:
    image: postgres:16
    container_name: airflow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - /mnt/data/volumes/airflow-db:/var/lib/postgresql/data
    networks:
      - orchestrator-net

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      - airflow-db
    command: >
      bash -c "
      pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
      airflow db migrate &&
      airflow users create
      --username ${_AIRFLOW_WWW_USER_USERNAME}
      --password ${_AIRFLOW_WWW_USER_PASSWORD}
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email admin@example.com || true
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    depends_on:
      - airflow-db
      - airflow-init
    command: >
      bash -c "
      pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
      airflow webserver
      "
    ports:
      - "8088:8080"
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    depends_on:
      - airflow-db
      - airflow-init
    command: >
      bash -c "
      pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
      airflow scheduler
      "
    restart: unless-stopped

networks:
  orchestrator-net:
    name: orchestrator-net
  ingest-net:
    external: true
    name: ingest_olist-net
